services:
  - type: web
    name: questionary
    env: ruby
    region: frankfurt
    plan: free
    branch: main
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails server"
    healthCheckPath: /up
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: questionary-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production

databases:
  - name: questionary-db
    region: frankfurt
    plan: free
    ipAllowList: []
