# This file should ensure the existence of records required to run the application.
# Run with: bin/rails db:seed
#
# Questions imported from: Evaluacion Tecnica preguntas 28-5-2026.xlsx

questions_data = [
  {
    item: 7,
    question_text: "Presión de formación SIDPP = 400 psi MW = 10 ppg TVD = 10,000 ft ¿Cuál es presión de formación?",
    option_a: "5,200 psi",
    option_b: "5,400 psi",
    option_c: "5,600 psi",
    option_d: "5,800 psi",
    correct_answer: "c",
  },
  {
    item: 47,
    question_text: "Durante un shut-in, si SIDPP = 300 psi y SICP = 500 psi, ¿qué indica esto?",
    option_a: "Influjo de agua",
    option_b: "Influjo de gas",
    option_c: "Diferencia normal por fricción",
    option_d: "Error en medición",
    correct_answer: "c",
  },
  {
    item: 74,
    question_text: "El RAP-F-006 es evidencia de:",
    option_a: "Operación del equipo",
    option_b: "Aseguramiento y verificación",
    option_c: "Producción",
    option_d: "Costos",
    correct_answer: "c",
  },
  {
    item: 79,
    question_text: "Con MW = 10.5 ppg, TVD = 10,000 ft y SIDPP = 500 psi, ¿cuál es el Kill Mud Weight?",
    option_a: "10.5 ppg",
    option_b: "11.46 ppg",
    option_c: "11.2 ppg",
    option_d: "11.5 ppg",
    correct_answer: "c",
  },
  {
    item: 80,
    question_text: "Si la SIDPP es 300 psi y la presión hidrostática es 5,000 psi, ¿cuál es la presión de formación?",
    option_a: "5,000 psi",
    option_b: "5,100 psi",
    option_c: "5,300 psi",
    option_d: "5,600 psi",
    correct_answer: "c",
  },
  {
    item: 81,
    question_text: "Gradiente de fractura = 0.80 psi/ft, zapato = 5,000 ft, MW = 10 ppg. ¿MAASP?",
    option_a: "800 psi",
    option_b: "1,000 psi",
    option_c: "1,200 psi",
    option_d: "1,400 psi",
    correct_answer: "c",
  },
  {
    item: 82,
    question_text: "MW = 10 ppg, TVD = 10,000 ft, pérdidas = 260 psi. ¿ECD?",
    option_a: "10.3 ppg",
    option_b: "10.5 ppg",
    option_c: "10.6 ppg",
    option_d: "11 ppg",
    correct_answer: "c",
  },
  {
    item: 83,
    question_text: "Capacidad anular = 0.05 bbl/ft, altura influjo = 150 ft. ¿Volumen?",
    option_a: "5 bbl",
    option_b: "7.5 bbl",
    option_c: "10 bbl",
    option_d: "12 bbl",
    correct_answer: "c",
  },
  {
    item: 84,
    question_text: "Presión bomba inicial = 1200 psi a 30 spm. ¿Presión a 20 spm?",
    option_a: "600 psi",
    option_b: "700 psi",
    option_c: "800 psi",
    option_d: "900 psi",
    correct_answer: "c",
  },
  {
    item: 85,
    question_text: "Si MW = 9.8 ppg y TVD = 9,000 ft, ¿presión hidrostática?",
    option_a: "4,000 psi",
    option_b: "4,500 psi",
    option_c: "4,586 psi",
    option_d: "5,000 psi",
    correct_answer: "c",
  },
  {
    item: 86,
    question_text: "SIDPP = 450 psi, MW = 10 ppg, TVD = 10,000 ft. ¿Presión de formación?",
    option_a: "5,200 psi",
    option_b: "5,400 psi",
    option_c: "5,650 psi",
    option_d: "6,000 psi",
    correct_answer: "c",
  },
  {
    item: 87,
    question_text: "Gradiente fractura = 0.75 psi/ft, zapato = 6,000 ft, MW = 10 ppg. ¿MAASP?",
    option_a: "800 psi",
    option_b: "1,200 psi",
    option_c: "1,380 psi",
    option_d: "1,800 psi",
    correct_answer: "c",
  },
  {
    item: 88,
    question_text: "MW = 10.5 ppg, TVD = 11,000 ft. ¿Presión hidrostática?",
    option_a: "5,500 psi",
    option_b: "6,006 psi",
    option_c: "6,300 psi",
    option_d: "6,800 psi",
    correct_answer: "c",
  },
  {
    item: 89,
    question_text: "SIDPP = 600 psi, MW = 10 ppg, TVD = 10,000 ft. ¿Kill MW?",
    option_a: "10.5",
    option_b: "10.96",
    option_c: "11.15",
    option_d: "11.5",
    correct_answer: "c",
  },
  {
    item: 90,
    question_text: "Capacidad anular = 0.04 bbl/ft, altura = 250 ft. ¿Volumen?",
    option_a: "8 bbl",
    option_b: "10 bbl",
    option_c: "12 bbl",
    option_d: "15 bbl",
    correct_answer: "c",
  },
  {
    item: 91,
    question_text: "MW = 9.5 ppg, TVD = 10,500 ft. ¿Presión hidrostática?",
    option_a: "4,900 psi",
    option_b: "5,187 psi",
    option_c: "5,500 psi",
    option_d: "6,000 psi",
    correct_answer: "c",
  },
  {
    item: 92,
    question_text: "Pérdidas fricción = 300 psi, MW = 10 ppg, TVD = 10,000 ft. ¿ECD?",
    option_a: "10.3",
    option_b: "10.6",
    option_c: "10.8",
    option_d: "11",
    correct_answer: "c",
  },
  {
    item: 93,
    question_text: "SIDPP = 350 psi, hidrostática = 5,200 psi. ¿Presión de formación?",
    option_a: "5,200",
    option_b: "5,350",
    option_c: "5,550",
    option_d: "5,700",
    correct_answer: "c",
  },
  {
    item: 94,
    question_text: "Gradiente = 0.78 psi/ft, zapato = 5,500 ft, MW = 10 ppg. ¿MAASP?",
    option_a: "900",
    option_b: "1,100",
    option_c: "1,330",
    option_d: "1,500",
    correct_answer: "c",
  },
  {
    item: 95,
    question_text: "MW = 11 ppg, TVD = 9,500 ft. ¿Presión hidrostática?",
    option_a: "5,000",
    option_b: "5,434",
    option_c: "5,800",
    option_d: "6,200",
    correct_answer: "c",
  },
  {
    item: 96,
    question_text: "SIDPP = 500 psi, TVD = 10,000 ft, MW = 10 ppg. ¿Kill MW?",
    option_a: "10.5",
    option_b: "10.96",
    option_c: "11.1",
    option_d: "11.5",
    correct_answer: "c",
  },
  {
    item: 97,
    question_text: "Capacidad = 0.06 bbl/ft, altura = 200 ft. ¿Volumen?",
    option_a: "8",
    option_b: "10",
    option_c: "12",
    option_d: "15",
    correct_answer: "c",
  },
  {
    item: 98,
    question_text: "Según GOP-G-053, ¿cuántas barreras mínimo deben existir en una intervención a pozo?",
    option_a: "1",
    option_b: "2",
    option_c: "3",
    option_d: "Ninguna",
    correct_answer: "b",
  },
  {
    item: 99,
    question_text: "En una intervención, ¿cuál es la barrera activa principal?",
    option_a: "BOP",
    option_b: "Árbol de navidad",
    option_c: "Columna hidrostática",
    option_d: "Choke",
    correct_answer: "c",
  },
  {
    item: 100,
    question_text: "Según GOP-G-046, ¿cuándo debe realizarse la aceptación del equipo?",
    option_a: "Después de iniciar operación",
    option_b: "Durante operación",
    option_c: "Antes de iniciar operación",
    option_d: "Al finalizar",
    correct_answer: "c",
  },
  {
    item: 101,
    question_text: "Si el RAP-F-006 presenta hallazgos impeditivos, ¿qué se debe hacer?",
    option_a: "Operar",
    option_b: "Registrar",
    option_c: "No iniciar operación",
    option_d: "Delegar",
    correct_answer: "c",
  },
  {
    item: 102,
    question_text: "Según HSE-M-011, ¿qué se debe hacer si no hay análisis de riesgos?",
    option_a: "Continuar",
    option_b: "Ajustar en campo",
    option_c: "Detener trabajo",
    option_d: "Delegar",
    correct_answer: "c",
  },
  {
    item: 103,
    question_text: "¿Quién puede detener una actividad insegura según HSE?",
    option_a: "Supervisor",
    option_b: "HSE",
    option_c: "Cualquier persona",
    option_d: "Operador",
    correct_answer: "c",
  },
  {
    item: 104,
    question_text: "Según GOP-G-053, ¿cada cuánto se deben realizar simulacros de control de pozo?",
    option_a: "7 días",
    option_b: "14 días",
    option_c: "21 días",
    option_d: "30 días",
    correct_answer: "c",
  },
  {
    item: 105,
    question_text: "Una intervención clasificada como C2 implica:",
    option_a: "Bajo riesgo",
    option_b: "Sin supervisión",
    option_c: "Mayor aseguramiento técnico",
    option_d: "No requiere planeación",
    correct_answer: "c",
  },
  {
    item: 106,
    question_text: "¿Quién es responsable de asegurar la certificación de well control?",
    option_a: "HSE",
    option_b: "Supervisor integral",
    option_c: "Operador",
    option_d: "Contratista",
    correct_answer: "b",
  },
  {
    item: 107,
    question_text: "Si durante operación se pierde una barrera de control de pozo:",
    option_a: "Continuar",
    option_b: "Registrar",
    option_c: "Detener operación",
    option_d: "Delegar",
    correct_answer: "c",
  },
  {
    item: 108,
    question_text: "Según GOP-G-046, el responsable de la integridad del equipo es:",
    option_a: "Company Man",
    option_b: "Ecopetrol",
    option_c: "Dueño del equipo",
    option_d: "HSE",
    correct_answer: "c",
  },
  {
    item: 109,
    question_text: "¿Se puede operar con certificados vencidos?",
    option_a: "Sí",
    option_b: "Solo temporal",
    option_c: "No",
    option_d: "Depende",
    correct_answer: "c",
  },
  {
    item: 110,
    question_text: "En SIMOPS, ¿qué se debe asegurar?",
    option_a: "Producción",
    option_b: "Coordinación de riesgos",
    option_c: "Velocidad",
    option_d: "Costos",
    correct_answer: "b",
  },
  {
    item: 111,
    question_text: "La guía HSE-M-011 establece que el trabajo debe:",
    option_a: "Ejecutarse rápido",
    option_b: "Ejecutarse sin riesgos",
    option_c: "Ejecutarse con control de riesgos",
    option_d: "Delegarse",
    correct_answer: "c",
  },
  {
    item: 112,
    question_text: "Según GOP-G-054, el objetivo de la intervención es:",
    option_a: "Reducir costos",
    option_b: "Mejorar o restaurar el pozo",
    option_c: "Cambiar equipo",
    option_d: "Incrementar personal",
    correct_answer: "b",
  },
  {
    item: 113,
    question_text: "Si el equipo no cumple con RAP-F-006:",
    option_a: "Operar",
    option_b: "Registrar",
    option_c: "No aceptar",
    option_d: "Delegar",
    correct_answer: "c",
  },
  {
    item: 114,
    question_text: "¿Quién emite el permiso de trabajo?",
    option_a: "AE",
    option_b: "AA",
    option_c: "AAL",
    option_d: "HSE",
    correct_answer: "c",
  },
  {
    item: 115,
    question_text: "Una desviación en barreras implica:",
    option_a: "Ajuste menor",
    option_b: "Riesgo crítico",
    option_c: "Sin impacto",
    option_d: "Registro",
    correct_answer: "b",
  },
  {
    item: 116,
    question_text: "El Company Man debe:",
    option_a: "Ejecutar operaciones",
    option_b: "Supervisar y asegurar cumplimiento",
    option_c: "Operar equipos",
    option_d: "Transportar",
    correct_answer: "b",
  },
  {
    item: 117,
    question_text: "Si no se cumplen guías Ecopetrol:",
    option_a: "No pasa nada",
    option_b: "Se continúa",
    option_c: "Se genera desviación contractual",
    option_d: "Se delega",
    correct_answer: "c",
  },
  {
    item: 118,
    question_text: "¿Cuál es el objetivo principal del control de trabajo?",
    option_a: "Reducir costos",
    option_b: "Aumentar producción",
    option_c: "Gestionar riesgos en la ejecución de actividades",
    option_d: "Mejorar tiempos",
    correct_answer: "c",
  },
  {
    item: 119,
    question_text: "El control de trabajo se basa en:",
    option_a: "Producción",
    option_b: "Planeación, ejecución, control y mejora",
    option_c: "Costos",
    option_d: "Logística",
    correct_answer: "b",
  },
  {
    item: 120,
    question_text: "Antes de iniciar un trabajo se debe:",
    option_a: "Ejecutar",
    option_b: "Delegar",
    option_c: "Identificar peligros y controles",
    option_d: "Registrar",
    correct_answer: "c",
  },
  {
    item: 121,
    question_text: "Si no existe análisis de riesgos:",
    option_a: "Se continúa",
    option_b: "Se ajusta en campo",
    option_c: "Se detiene el trabajo",
    option_d: "Se delega",
    correct_answer: "c",
  },
  {
    item: 122,
    question_text: "El permiso de trabajo es:",
    option_a: "Opcional",
    option_b: "Informativo",
    option_c: "Obligatorio para actividades no rutinarias",
    option_d: "Solo administrativo",
    correct_answer: "c",
  },
  {
    item: 123,
    question_text: "¿Quién ejecuta el trabajo?",
    option_a: "AA",
    option_b: "AAL",
    option_c: "AE",
    option_d: "HSE",
    correct_answer: "c",
  },
  {
    item: 124,
    question_text: "¿Quién autoriza el trabajo?",
    option_a: "AE",
    option_b: "AA",
    option_c: "AAL",
    option_d: "Supervisor",
    correct_answer: "c",
  },
  {
    item: 125,
    question_text: "Durante la ejecución del trabajo se debe:",
    option_a: "Ignorar riesgos",
    option_b: "Monitorear condiciones",
    option_c: "Delegar",
    option_d: "Registrar al final",
    correct_answer: "b",
  },
  {
    item: 126,
    question_text: "Si cambian las condiciones del trabajo:",
    option_a: "Continuar",
    option_b: "Ajustar después",
    option_c: "Reevaluar riesgos",
    option_d: "Delegar",
    correct_answer: "c",
  },
  {
    item: 127,
    question_text: "¿Quién puede detener un trabajo inseguro?",
    option_a: "Supervisor",
    option_b: "HSE",
    option_c: "Cualquier persona",
    option_d: "Operador",
    correct_answer: "c",
  },
  {
    item: 128,
    question_text: "El análisis de riesgos debe:",
    option_a: "Archivarse",
    option_b: "Ignorarse",
    option_c: "Aplicarse en campo",
    option_d: "Delegarse",
    correct_answer: "c",
  },
  {
    item: 129,
    question_text: "El control de trabajo aplica para:",
    option_a: "Solo mantenimiento",
    option_b: "Solo producción",
    option_c: "Todas las actividades",
    option_d: "Solo perforación",
    correct_answer: "c",
  },
  {
    item: 130,
    question_text: "El permiso de trabajo debe estar:",
    option_a: "Cerrado",
    option_b: "Vigente",
    option_c: "Archivado",
    option_d: "Firmado después",
    correct_answer: "b",
  },
  {
    item: 131,
    question_text: "El objetivo de SIMOPS es:",
    option_a: "Aumentar producción",
    option_b: "Coordinar actividades simultáneas",
    option_c: "Reducir personal",
    option_d: "Acelerar trabajo",
    correct_answer: "b",
  },
  {
    item: 132,
    question_text: "El control de trabajo busca:",
    option_a: "Evitar accidentes",
    option_b: "Reducir costos",
    option_c: "Controlar tiempos",
    option_d: "Aumentar velocidad",
    correct_answer: "a",
  },
  {
    item: 133,
    question_text: "Una condición insegura debe:",
    option_a: "Ignorarse",
    option_b: "Registrarse",
    option_c: "Corregirse",
    option_d: "Delegarse",
    correct_answer: "c",
  },
  {
    item: 134,
    question_text: "El cierre del trabajo incluye:",
    option_a: "Solo reporte",
    option_b: "Evaluación de resultados",
    option_c: "Archivo",
    option_d: "Firma",
    correct_answer: "b",
  },
  {
    item: 135,
    question_text: "La comunicación del trabajo es:",
    option_a: "Opcional",
    option_b: "Crítica",
    option_c: "Administrativa",
    option_d: "Secundaria",
    correct_answer: "b",
  },
  {
    item: 136,
    question_text: "El control de trabajo exige:",
    option_a: "Velocidad",
    option_b: "Disciplina operativa",
    option_c: "Reducción de personal",
    option_d: "Costos",
    correct_answer: "b",
  },
  {
    item: 137,
    question_text: "Si no se cumple el control de trabajo:",
    option_a: "No pasa nada",
    option_b: "Se registra",
    option_c: "Se incrementa el riesgo",
    option_d: "Se delega",
    correct_answer: "c",
  },
  {
    item: 140,
    question_text: "¿Cuál es el objetivo principal del estándar API 53?",
    option_a: "Reducir costos",
    option_b: "Establecer requisitos para sistemas de control de pozo",
    option_c: "Mejorar producción",
    option_d: "Controlar logística",
    correct_answer: "b",
  },
  {
    item: 141,
    question_text: "El sistema BOP está diseñado para:",
    option_a: "Producir hidrocarburos",
    option_b: "Controlar presión del pozo",
    option_c: "Medir caudal",
    option_d: "Transportar fluidos",
    correct_answer: "b",
  },
  {
    item: 142,
    question_text: "¿Cuántas barreras se deben garantizar según buenas prácticas de control de pozo?",
    option_a: "1",
    option_b: "2",
    option_c: "3",
    option_d: "Ninguna",
    correct_answer: "b",
  },
  {
    item: 143,
    question_text: "El acumulador del BOP sirve para:",
    option_a: "Medir presión",
    option_b: "Almacenar energía hidráulica",
    option_c: "Controlar flujo",
    option_d: "Bombear lodo",
    correct_answer: "b",
  },
  {
    item: 144,
    question_text: "Una prueba de presión del BOP debe:",
    option_a: "Omitirse",
    option_b: "Realizarse periódicamente",
    option_c: "Solo hacerse al final",
    option_d: "Delegarse",
    correct_answer: "b",
  },
  {
    item: 145,
    question_text: "El choke manifold permite:",
    option_a: "Cerrar el pozo",
    option_b: "Controlar flujo y presión",
    option_c: "Medir volumen",
    option_d: "Bombear fluido",
    correct_answer: "b",
  },
  {
    item: 146,
    question_text: "La línea kill se usa para:",
    option_a: "Producción",
    option_b: "Inyección de fluido al pozo",
    option_c: "Medición",
    option_d: "Control eléctrico",
    correct_answer: "b",
  },
  {
    item: 147,
    question_text: "Si el BOP presenta fuga en prueba:",
    option_a: "Continuar",
    option_b: "Registrar",
    option_c: "No operar",
    option_d: "Delegar",
    correct_answer: "c",
  },
  {
    item: 148,
    question_text: "El tiempo de respuesta del BOP debe ser:",
    option_a: "Lento",
    option_b: "Inmediato",
    option_c: "Opcional",
    option_d: "Variable",
    correct_answer: "b",
  },
  {
    item: 150,
    question_text: "El panel de control del BOP debe:",
    option_a: "Ser opcional",
    option_b: "Permitir operación remota",
    option_c: "Solo ser local",
    option_d: "No ser usado",
    correct_answer: "b",
  },
  {
    item: 151,
    question_text: "Un ram preventer sirve para:",
    option_a: "Medir presión",
    option_b: "Sellar el pozo",
    option_c: "Bombear fluido",
    option_d: "Controlar torque",
    correct_answer: "b",
  },
  {
    item: 152,
    question_text: "El BOP anular permite:",
    option_a: "Cortar tubería",
    option_b: "Sellar alrededor de la tubería",
    option_c: "Medir volumen",
    option_d: "Bombear",
    correct_answer: "b",
  },
  {
    item: 153,
    question_text: "Si el acumulador no tiene presión suficiente:",
    option_a: "Operar",
    option_b: "Ajustar después",
    option_c: "No iniciar operación",
    option_d: "Delegar",
    correct_answer: "c",
  },
  {
    item: 154,
    question_text: "El sistema de control del BOP debe ser:",
    option_a: "Manual",
    option_b: "Automático y redundante",
    option_c: "Opcional",
    option_d: "Simple",
    correct_answer: "b",
  },
  {
    item: 155,
    question_text: "La prueba de baja presión se realiza para:",
    option_a: "Verificar fugas",
    option_b: "Medir volumen",
    option_c: "Controlar flujo",
    option_d: "Bombear",
    correct_answer: "a",
  },
  {
    item: 156,
    question_text: "La prueba de alta presión verifica:",
    option_a: "Integridad estructural",
    option_b: "Producción",
    option_c: "Caudal",
    option_d: "Torque",
    correct_answer: "a",
  },
  {
    item: 157,
    question_text: "El BOP debe ser inspeccionado:",
    option_a: "Nunca",
    option_b: "Solo al final",
    option_c: "Antes de operar",
    option_d: "Después de operar",
    correct_answer: "c",
  },
  {
    item: 158,
    question_text: "Si falla el sistema de control remoto:",
    option_a: "Continuar",
    option_b: "Usar sistema alterno",
    option_c: "Ignorar",
    option_d: "Registrar",
    correct_answer: "b",
  },
  {
    item: 159,
    question_text: "El mantenimiento del BOP debe ser:",
    option_a: "Opcional",
    option_b: "Periódico",
    option_c: "Eventual",
    option_d: "Delegado",
    correct_answer: "b",
  },
  {
    item: 160,
    question_text: "Si el sistema BOP no cumple API 53:",
    option_a: "Operar",
    option_b: "Ajustar después",
    option_c: "No operar",
    option_d: "Delegar",
    correct_answer: "c",
  },
  {
    item: 161,
    question_text: "El aumento simultáneo de torque y arrastre indica:",
    option_a: "Flujo estable",
    option_b: "Pegadura mecánica",
    option_c: "Influjo de gas",
    option_d: "Falla de bomba",
    correct_answer: "b",
  },
  {
    item: 162,
    question_text: "La pega diferencial ocurre cuando:",
    option_a: "Hay pérdida de circulación",
    option_b: "La presión diferencial empuja la tubería contra la pared del pozo",
    option_c: "Hay vibración",
    option_d: "Hay bajo torque",
    correct_answer: "b",
  },
  {
    item: 163,
    question_text: "Indicador temprano de stuck pipe:",
    option_a: "Flujo constante",
    option_b: "Aumento de torque",
    option_c: "Baja presión",
    option_d: "Caudal estable",
    correct_answer: "b",
  },
  {
    item: 164,
    question_text: "Primera acción ante stuck pipe:",
    option_a: "Forzar tubería",
    option_b: "Aplicar jar inmediatamente",
    option_c: "Diagnosticar causa",
    option_d: "Cortar tubería",
    correct_answer: "c",
  },
  {
    item: 165,
    question_text: "La pegadura diferencial es más probable en:",
    option_a: "Alta permeabilidad",
    option_b: "Baja presión",
    option_c: "Alta vibración",
    option_d: "Bajo torque",
    correct_answer: "a",
  },
  {
    item: 166,
    question_text: "El sobrepull excesivo puede generar:",
    option_a: "Liberación inmediata",
    option_b: "Daño en tubería",
    option_c: "Mejor flujo",
    option_d: "Control del pozo",
    correct_answer: "b",
  },
  {
    item: 167,
    question_text: "Para prevenir stuck pipe se debe:",
    option_a: "Aumentar velocidad",
    option_b: "Monitorear torque y arrastre",
    option_c: "Reducir vigilancia",
    option_d: "Ignorar parámetros",
    correct_answer: "b",
  },
  {
    item: 168,
    question_text: "Una caída de presión junto con aumento de torque puede indicar:",
    option_a: "Influjo",
    option_b: "Pérdida de circulación y riesgo de pegadura",
    option_c: "Flujo normal",
    option_d: "Error",
    correct_answer: "b",
  },
  {
    item: 169,
    question_text: "El uso de jars se recomienda:",
    option_a: "Sin análisis",
    option_b: "Después de diagnóstico",
    option_c: "Siempre",
    option_d: "Nunca",
    correct_answer: "b",
  },
  {
    item: 170,
    question_text: "La pegadura mecánica ocurre por:",
    option_a: "Presión diferencial",
    option_b: "Obstrucción física",
    option_c: "Caudal",
    option_d: "Flujo",
    correct_answer: "b",
  },
  {
    item: 171,
    question_text: "El diferencial de presión aumenta con:",
    option_a: "Bajo MW",
    option_b: "Alto MW",
    option_c: "Bajo torque",
    option_d: "Alta velocidad",
    correct_answer: "b",
  },
  {
    item: 172,
    question_text: "Un aumento de arrastre al sacar tubería indica:",
    option_a: "Pozo limpio",
    option_b: "Riesgo de stuck pipe",
    option_c: "Flujo normal",
    option_d: "Baja presión",
    correct_answer: "b",
  },
  {
    item: 173,
    question_text: "La limpieza del pozo es clave para:",
    option_a: "Producción",
    option_b: "Evitar pegaduras",
    option_c: "Medición",
    option_d: "Caudal",
    correct_answer: "b",
  },
  {
    item: 174,
    question_text: "Si la tubería no rota ni se mueve:",
    option_a: "Continuar",
    option_b: "Aumentar torque",
    option_c: "Evaluar condición",
    option_d: "Ignorar",
    correct_answer: "c",
  },
  {
    item: 175,
    question_text: "El monitoreo de drag permite:",
    option_a: "Medir presión",
    option_b: "Detectar condiciones anormales",
    option_c: "Controlar flujo",
    option_d: "Bombear",
    correct_answer: "b",
  },
  {
    item: 176,
    question_text: "Una zona de alta presión diferencial puede generar:",
    option_a: "Flujo",
    option_b: "Pegadura",
    option_c: "Producción",
    option_d: "Caudal",
    correct_answer: "b",
  },
  {
    item: 177,
    question_text: "La velocidad excesiva en maniobras puede:",
    option_a: "Mejorar operación",
    option_b: "Generar pegadura",
    option_c: "Reducir torque",
    option_d: "Controlar presión",
    correct_answer: "b",
  },
  {
    item: 178,
    question_text: "El uso de lubricantes ayuda a:",
    option_a: "Reducir presión",
    option_b: "Reducir fricción",
    option_c: "Aumentar torque",
    option_d: "Controlar flujo",
    correct_answer: "b",
  },
  {
    item: 179,
    question_text: "El análisis de stuck pipe debe incluir:",
    option_a: "Solo presión",
    option_b: "Torque, drag, lodo y condiciones del pozo",
    option_c: "Solo caudal",
    option_d: "Solo velocidad",
    correct_answer: "b",
  },
  {
    item: 180,
    question_text: "Si no se controla el stuck pipe:",
    option_a: "No pasa nada",
    option_b: "Se pierde tiempo",
    option_c: "Puede generar pérdida de pozo",
    option_d: "Se ajusta",
    correct_answer: "c",
  },
  {
    item: 181,
    question_text: "Si el BOP anular no sella completamente durante la prueba:",
    option_a: "Continuar operación",
    option_b: "Registrar y operar",
    option_c: "No aceptar el equipo",
    option_d: "Delegar",
    correct_answer: "c",
  },
  {
    item: 182,
    question_text: "El acumulador debe garantizar:",
    option_a: "Producción",
    option_b: "Energía suficiente para cerrar el BOP",
    option_c: "Caudal",
    option_d: "Velocidad",
    correct_answer: "b",
  },
  {
    item: 183,
    question_text: "Si la línea kill presenta fuga:",
    option_a: "Operar",
    option_b: "Registrar",
    option_c: "No iniciar operación",
    option_d: "Delegar",
    correct_answer: "c",
  },
  {
    item: 184,
    question_text: "El choke manifold debe:",
    option_a: "Medir volumen",
    option_b: "Controlar presión y flujo",
    option_c: "Producir",
    option_d: "Transportar",
    correct_answer: "b",
  },
  {
    item: 185,
    question_text: "El malacate debe ser inspeccionado para:",
    option_a: "Producción",
    option_b: "Integridad estructural",
    option_c: "Flujo",
    option_d: "Caudal",
    correct_answer: "b",
  },
  {
    item: 186,
    question_text: "Si el cable de acero presenta desgaste crítico:",
    option_a: "Continuar",
    option_b: "Registrar",
    option_c: "No operar",
    option_d: "Delegar",
    correct_answer: "c",
  },
  {
    item: 187,
    question_text: "El sistema de frenos del malacate debe:",
    option_a: "Ser opcional",
    option_b: "Estar operativo y probado",
    option_c: "Ignorarse",
    option_d: "Ajustarse después",
    correct_answer: "b",
  },
  {
    item: 188,
    question_text: "Si el sistema rotario presenta vibración excesiva:",
    option_a: "Operar",
    option_b: "Evaluar condición",
    option_c: "Ignorar",
    option_d: "Delegar",
    correct_answer: "b",
  },
  {
    item: 189,
    question_text: "El sistema de potencia debe garantizar:",
    option_a: "Flujo",
    option_b: "Energía estable para operación",
    option_c: "Presión",
    option_d: "Caudal",
    correct_answer: "b",
  },
  {
    item: 190,
    question_text: "El sistema eléctrico debe cumplir:",
    option_a: "Solo operación",
    option_b: "Normas de seguridad industrial",
    option_c: "Producción",
    option_d: "Caudal",
    correct_answer: "b",
  },
  {
    item: 191,
    question_text: "Si hay cables expuestos:",
    option_a: "Operar",
    option_b: "Registrar",
    option_c: "No aceptar",
    option_d: "Delegar",
    correct_answer: "c",
  },
  {
    item: 192,
    question_text: "El sistema de bombeo debe:",
    option_a: "Medir",
    option_b: "Garantizar circulación adecuada",
    option_c: "Producir",
    option_d: "Controlar torque",
    correct_answer: "b",
  },
  {
    item: 193,
    question_text: "Si hay fuga en líneas de fluido:",
    option_a: "Operar",
    option_b: "Registrar",
    option_c: "Corregir antes de operar",
    option_d: "Delegar",
    correct_answer: "c",
  },
  {
    item: 194,
    question_text: "La torre debe ser inspeccionada para:",
    option_a: "Producción",
    option_b: "Integridad estructural",
    option_c: "Caudal",
    option_d: "Flujo",
    correct_answer: "b",
  },
  {
    item: 195,
    question_text: "Si hay fisuras en estructura:",
    option_a: "Operar",
    option_b: "Registrar",
    option_c: "No aceptar",
    option_d: "Delegar",
    correct_answer: "c",
  },
  {
    item: 196,
    question_text: "El equipo debe contar con:",
    option_a: "Manual",
    option_b: "Certificados vigentes",
    option_c: "Registro",
    option_d: "Archivo",
    correct_answer: "b",
  },
  {
    item: 197,
    question_text: "Si los certificados están vencidos:",
    option_a: "Operar",
    option_b: "Registrar",
    option_c: "No aceptar",
    option_d: "Delegar",
    correct_answer: "c",
  },
  {
    item: 198,
    question_text: "El equipo debe contar con:",
    option_a: "Producción",
    option_b: "Sistemas de seguridad operativos",
    option_c: "Caudal",
    option_d: "Torque",
    correct_answer: "b",
  },
  {
    item: 199,
    question_text: "Si no hay señalización de seguridad:",
    option_a: "Operar",
    option_b: "Registrar",
    option_c: "Corregir antes de operar",
    option_d: "Delegar",
    correct_answer: "c",
  },
  {
    item: 200,
    question_text: "El objetivo del RAP-F-006 es:",
    option_a: "Reducir costos",
    option_b: "Asegurar condiciones seguras del equipo",
    option_c: "Aumentar producción",
    option_d: "Medir",
    correct_answer: "b",
  },
  {
    item: 201,
    question_text: "SIDPP = 500 psi MW = 10 ppg TVD = 10,000 ft ¿Cuál es el Kill Mud Weight?",
    option_a: "10.5 ppg",
    option_b: "10.96 ppg",
    option_c: "11.2 ppg",
    option_d: "11.5 ppg",
    correct_answer: "b",
  },
  {
    item: 202,
    question_text: "SICP = 700 psi y SIDPP = 400 psi. ¿Qué indica?",
    option_a: "Influjo de agua",
    option_b: "Influjo de gas",
    option_c: "Error de medición",
    option_d: "Pérdida",
    correct_answer: "b",
  },
  {
    item: 203,
    question_text: "ICP = 1200 psi SIDPP = 500 psi ¿Cuál es la FCP?",
    option_a: "1200 psi",
    option_b: "700 psi",
    option_c: "1700 psi",
    option_d: "500 psi",
    correct_answer: "b",
  },
  {
    item: 204,
    question_text: "Kill rate = 30 spm → presión 1200 psi Nueva tasa = 20 spm Nueva presión:",
    option_a: "600 psi",
    option_b: "800 psi",
    option_c: "900 psi",
    option_d: "1000 psi",
    correct_answer: "b",
  },
  {
    item: 205,
    question_text: "Si la presión casing aumenta durante shut-in:",
    option_a: "No pasa nada",
    option_b: "Indica migración de gas",
    option_c: "Indica pérdida",
    option_d: "Error",
    correct_answer: "b",
  },
  {
    item: 206,
    question_text: "Volumen total sistema = 150 bbl Caudal = 5 bpm Tiempo para circular:",
    option_a: "20 min",
    option_b: "25 min",
    option_c: "30 min",
    option_d: "35 min",
    correct_answer: "c",
  },
  {
    item: 207,
    question_text: "MAASP = 1400 psi Presión casing actual = 1500 psi ¿Qué hacer?",
    option_a: "Continuar",
    option_b: "Detener operación",
    option_c: "Reducir presión",
    option_d: "Ignorar",
    correct_answer: "c",
  },
  {
    item: 208,
    question_text: "MW = 10 ppg Pérdidas = 260 psi TVD = 10,000 ft ECD:",
    option_a: "10.3",
    option_b: "10.5",
    option_c: "10.6",
    option_d: "11",
    correct_answer: "b",
  },
  {
    item: 209,
    question_text: "SIDPP = 300 psi SICP = 300 psi Tipo de influjo:",
    option_a: "Gas",
    option_b: "Agua",
    option_c: "Petróleo",
    option_d: "Ninguno",
    correct_answer: "b",
  },
  {
    item: 210,
    question_text: "Si no se mantiene presión constante en método del perforador:",
    option_a: "No pasa nada",
    option_b: "Riesgo de blowout",
    option_c: "Baja producción",
    option_d: "Error menor",
    correct_answer: "b",
  },
  {
    item: 211,
    question_text: "Capacidad anular = 0.05 bbl/ft Altura = 200 ft Volumen influjo:",
    option_a: "5",
    option_b: "10",
    option_c: "12",
    option_d: "15",
    correct_answer: "b",
  },
  {
    item: 212,
    question_text: "Presión formación = 5800 psi Hidrostática = 5200 psi SIDPP:",
    option_a: "400",
    option_b: "500",
    option_c: "600",
    option_d: "700",
    correct_answer: "c",
  },
  {
    item: 213,
    question_text: "Gradiente formación = 0.56 psi/ft TVD = 10,000 ft Presión:",
    option_a: "5200",
    option_b: "5400",
    option_c: "5600",
    option_d: "5800",
    correct_answer: "c",
  },
  {
    item: 214,
    question_text: "Durante circulación la presión cae:",
    option_a: "Mejora control",
    option_b: "Riesgo de influjo",
    option_c: "No pasa nada",
    option_d: "Error",
    correct_answer: "b",
  },
  {
    item: 215,
    question_text: "Kill sheet permite:",
    option_a: "Medir producción",
    option_b: "Planear control del pozo",
    option_c: "Reducir costos",
    option_d: "Controlar torque",
    correct_answer: "b",
  },
  {
    item: 216,
    question_text: "ICP se define como:",
    option_a: "Presión final",
    option_b: "Presión inicial de circulación",
    option_c: "Presión de formación",
    option_d: "Presión hidrostática",
    correct_answer: "b",
  },
  {
    item: 217,
    question_text: "FCP es:",
    option_a: "Presión máxima",
    option_b: "Presión final de circulación",
    option_c: "Presión inicial",
    option_d: "Presión casing",
    correct_answer: "b",
  },
  {
    item: 218,
    question_text: "Si la presión aumenta durante circulación:",
    option_a: "Correcto",
    option_b: "Riesgo de fractura",
    option_c: "No importa",
    option_d: "Error",
    correct_answer: "b",
  },
  {
    item: 219,
    question_text: "El método volumétrico se usa cuando:",
    option_a: "Hay bomba",
    option_b: "No se puede circular",
    option_c: "Hay producción",
    option_d: "Hay flujo",
    correct_answer: "b",
  },
  {
    item: 220,
    question_text: "El objetivo del well control es:",
    option_a: "Producir",
    option_b: "Mantener control de presión",
    option_c: "Reducir costos",
    option_d: "Aumentar caudal",
    correct_answer: "b",
  },
]

questions_data.each do |q|
  Question.find_or_create_by!(item: q[:item]) do |question|
    question.question_text = q[:question_text]
    question.option_a = q[:option_a]
    question.option_b = q[:option_b]
    question.option_c = q[:option_c]
    question.option_d = q[:option_d]
    question.correct_answer = q[:correct_answer]
  end
end

puts "Done! #{Question.count} questions in database."
